#!/usr/local/bin/python3

import timeit
import sys

if __name__ == "__main__":
	elapsed = []

	if len(sys.argv) != 2:
		print("Syntax: bench <program>")
		exit(1)

	elapsed = timeit.repeat('os.system("' +
				sys.argv[1] + ' 1 > /dev/null")',
				setup="import os", repeat=1000, number=1)

	print("{} execute en {:.4f}s".format(sys.argv[1],min(elapsed)))

