#!/usr/local/bin/python3

import timeit
import sys

def trace(i,s):
	print("{:d},{:.4f}".format(i,s))

def run(i):
	s = max(timeit.repeat('os.system("java -cp bin JTest ' + str(i) + '")', setup="import os", repeat=1, number=1))
	return s
	
if __name__ == "__main__":
	launch = run(1)
	trace(1,launch)
	for i in range(2,100):
		elapsed = run(i)
		trace(i,(elapsed-launch)/(i-1))

